<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Tom Scheduikat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js')
            ->prependFile($this->basePath() . '/js/jquery.carouFredSel-6.2.1-packed.js')
            ->prependFile($this->basePath() . '/js/jquery.touchSwipe.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

    </head>
    <body data-spy="scroll">
    <div id="wrapper">
        <div class="pictures">
            <div id="carousel">
                <img src="<?php echo $this->basePath() . "/img/carousel/1.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/2.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/3.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/4.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/5.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/6.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/7.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/8.JPG";?>" width="200" height="200" />
                <img src="<?php echo $this->basePath() . "/img/carousel/9.JPG";?>" width="200" height="200" />
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div id="content" class="container">
        <?php echo $this->content; ?>
    </div>
    <?php echo $this->inlineScript() ?>
    </body>
</html>
