<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Tom Scheduikat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js')
            ->prependFile($this->basePath() . '/js/jquery.carouFredSel-6.2.1-packed.js')
            ->prependFile($this->basePath() . '/js/jquery.touchSwipe.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

    </head>
    <body data-spy="scroll">
    <div id="wrapper">
        <div id="carousel">
            <img src="img/carousel/1.jpg" width="400" height="400" />
            <img src="img/carousel/2.jpg" width="400" height="400" />
            <img src="img/carousel/3.jpg" width="400" height="400" />
            <img src="img/carousel/4.jpg" width="400" height="400" />
            <img src="img/carousel/5.jpg" width="400" height="400" />
            <img src="img/carousel/6.jpg" width="400" height="400" />
            <img src="img/carousel/7.jpg" width="400" height="400" />
            <img src="img/carousel/8.jpg" width="400" height="400" />
            <img src="img/carousel/9.jpg" width="400" height="400" />
        </div>
    </div>
    <div id="navbar" class="container">
        <div class="navbar-inner">
            <ul class="nav nav-tabs navbar-fixed-bottom nav-stacked mainNavigation">
                <li><a href="#wrapper">Home</a></li>
                <li><a href="#profile">Profile</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
        <div id="content" class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
