<?php namespace Application; ?>
<div class="application">
    <div class="jumbotron">
        <div class="applicationText">
            <?php echo $this->translate('[APPLICATION_APPLICATIONTEXT]');?>
        </div>
        <div class="picture">
            <div class="col-sm-6 col-md-2">
                <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Foto.jpg"></a>
            </div>
        </div>
    </div>

    <div class="cv">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <th><?php echo $this->translate("[APPLICATION_PERSONAL]")?>:</th>
                    <th>&nbsp;</th>
                </thead>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_NAME]");?>:</td>
                    <td>Scheduikat</td>
                </tr>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_FIRSTNAME]");?>:</td>
                    <td>Tom</td>
                </tr>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_ADDRESS]");?>:</td>
                    <td>Frankenstraße 29, 18439 Stralsund</td>
                </tr>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_MOBILE]");?>:</td>
                    <td>0152 548 626 84</td>
                </tr>
                <tr>
                    <td>E-Mail:</td>
                    <td>Tom.Scheduikat@googlemail.com</td>
                </tr>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_BIRTHDAY]");?>:</td>
                    <td>8. <?php echo $this->translate("[APPLICATION_BIRTHDAY_MARCH]");?> 1991</td>
                </tr>
                <tr>
                    <td><?php echo $this->translate("[APPLICATION_CIVIL]");?>:</td>
                    <td><?php echo $this->translate("[APPLICATION_CIVIL_TEXT]");?></td>
                </tr>
            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th><?php echo $this->translate("[APPLICATION_WORK]");?>:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <?php echo $this->translate("[APPLICATION_WORK_1]");?>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_WORK_2]");?>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_WORK_3]");?>
                </tr>

            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th><?php echo $this->translate("[APPLICATION_EDUCATION]");?>:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <?php echo $this->translate("[APPLICATION_EDUCATION_1]");?>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_EDUCATION_2]");?>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_EDUCATION_3]");?>
                </tr>
            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th><?php echo $this->translate("[APPLICATION_QUALIFICATION]");?>:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <?php echo $this->translate("[APPLICATION_QUALIFICATION_LANG]");?>
                </tr>
                <tr>
                    <td>Frontend:</td>
                    <td>
                        CSS2/CSS3<br>
                        HTML4/HTML5<br>
                        Javascript (jQuery)<br>
                        Bootstrap
                    </td>
                </tr>
                <tr>
                    <td>Backend:</td>
                    <td>
                        PHP 5.2/5.3/5.4<br>
                        Zend Framework 1 / 2 <br>
                        MYSQL <br>
                        Doctrine
                    </td>
                </tr>
                <tr>
                    <td>IDE's:</td>
                    <td>
                        PHP Storm <br>
                        Eclipse <br>
                        Zend Studio
                    </td>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_QUALIFICATION_DIFFERENT]");?>
                </tr>
                <tr>
                    <?php echo $this->translate("[APPLICATION_QUALIFICATION_HUMAN]");?>
                </tr>
            </table>
        </div>
    </div>
    <div class="pictures row">
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Zeugnis_IHK.JPG" alt="Zeugnis IHK"></a>
        </div>
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Zeugnis_FHSR.JPG" alt="Zeugnis FHSR"></a>
        </div>
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Praktikanteneinschaetzung.JPG" alt="Praktikum"></a>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <img src="/img/application/Foto.JPG">
                </div>
            </div>
        </div>
    </div>
</div>