<div class="application">
    <div class="jumbotron">
        <div class="applicationText">
            <p>Sehr geehrte Damen und Herren,</p><br>
            <p>wenn Sie einen Mitarbeiter suchen, der sich schnell in neue Herausforderungen einarbeiten kann, der für
                Probleme kreative sowie fachlich hervorragende Lösungen findet und jemanden, der zielstrebig der
                Firmenphilosophie nacheifert, dann sind sie jetzt fündig geworden!</p>
            <p>Zum gegenwärtigen Zeitpunkt arbeite ich als Junior Softwareentwickler bei der Unister GmbH in Stralsund.
                (Aus persönlichen Gründen jedoch, werde ich jedoch das Unternehmen verlassen müssen) Gerne möchte ich
                meine bereits vorhandenen Kenntnisse und Fähigkeiten, welche ich ebenfalls in meiner Ausbildung zum
                Fachinformatiker erworben habe, vertiefen und ausbauen. Ich bin mir sicher, dass ich Ihr Team mit
                meinen Stärken erfolgreich unterstützen kann.</p>
            <p>Für meine Zukunft in diesem Beruf erhoffe ich mir in Ihrem Haus einen heraus-fordernden, kreativen und
                abwechslungsreichen Arbeitsplatz. Gerne würde ich Sie in einem persönlichen Gespräch davon überzeugen,
                dass eine Tätigkeit in Ihrem Hause genau meinen Vorstellungen entspricht
                und dies der Sinn meiner beruflichen Zukunft darstellt.</p>
        </div>
        <div class="picture">
            <div class="col-sm-6 col-md-2">
                <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Foto.jpg"></a>
            </div>
        </div>
    </div>

    <div class="cv">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <th>Persönliche Daten:</th>
                    <th>&nbsp;</th>
                </thead>
                <tr>
                    <td>Name:</td>
                    <td>Scheduikat</td>
                </tr>
                <tr>
                    <td>Vorname:</td>
                    <td>Tom</td>
                </tr>
                <tr>
                    <td>Adresse:</td>
                    <td>Frankenstraße 29, 18439 Stralsund</td>
                </tr>
                <tr>
                    <td>Telefon:</td>
                    <td>0152 548 626 84</td>
                </tr>
                <tr>
                    <td>E-Mail:</td>
                    <td>Tom.Scheduikat@googlemail.com</td>
                </tr>
                <tr>
                    <td>Geburtsdatum:</td>
                    <td>8. März 1991</td>
                </tr>
                <tr>
                    <td>Zivilstand:</td>
                    <td>ledig</td>
                </tr>
            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th>Berufliche Erfahrungen:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <td>09/2012 – heute</td>
                    <td>Unister GmbH Stralsund<br>
                        Junior Softwareentwickler
                    </td>
                </tr>
                <tr>
                    <td>01/2011 – 04/2012</td>
                    <td>Cinestar Stralsund<br>
                        Studentische Nebentätigkeit
                    </td>
                </tr>
                <tr>
                    <td>09/2009 – 08/2010</td>
                    <td>IT-College Putbus gGmbH<br>
                        Praktikum in der Administration
                    </td>
                </tr>

            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th>Ausbildung:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <td>09/2010 – 08/2012</td>
                    <td>Fachhochschule Stralsund<br>
                        Angewandte Informatik – <br>
                        Informations- und Kommunikationstechnik
                    </td>
                </tr>
                <tr>
                    <td>09/2009 – 08/2010</td>
                    <td>IT-College Putbus gGmbH<br>
                        Ausbildung Fachinformatiker / <br>
                        Anwendungsentwicklung
                    </td>
                </tr>
                <tr>
                    <td>07/2007 – 08/2009</td>
                    <td>IT-College Putbus gGmbH <br>
                        Ausbildung staatlich geprüfter <br>
                        Technischer Assistent / <br>
                        Fachhochschulreife

                    </td>
                </tr>
            </table>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <th>Qualifikationen:</th>
                <th>&nbsp;</th>
                </thead>
                <tr>
                    <td>Sprachen</td>
                    <td>Deutsch(Muttersprache)<br>
                        Englisch
                    </td>
                </tr>
                <tr>
                    <td>Frontend:</td>
                    <td>
                        CSS2/CSS3<br>
                        HTML4/HTML5<br>
                        Javascript (jQuery)<br>
                        Bootstrap
                    </td>
                </tr>
                <tr>
                    <td>Backend:</td>
                    <td>
                        PHP 5.2/5.3/5.4<br>
                        Zend Framework 1 / 2 <br>
                        MYSQL <br>
                        Doctrine
                    </td>
                </tr>
                <tr>
                    <td>IDE's:</td>
                    <td>
                        PHP Storm <br>
                        Eclipse <br>
                        Zend Studio
                    </td>
                </tr>
                <tr>
                    <td>Verschiedenes:</td>
                    <td>
                        gute Windowskenntnisse<br>
                        gute Linuxkenntnisse<br>
                        Umgang mit Microsoft Office, Libre/Open Office
                    </td>
                </tr>
                <tr>
                    <td>Menschliches:</td>
                    <td>
                        Strukturierte Arbeitsweise<br>
                        Teamfähigkeit<br>
                        Kreative Ideen<br>
                        Organisationstalent<br>
                        Stressrobust
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="pictures row">
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Zeugnis_IHK.jpg" alt="Zeugnis IHK"></a>
        </div>
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Zeugnis_FHSR.jpg" alt="Zeugnis FHSR"></a>
        </div>
        <div class="col-sm-6 col-md-2">
            <a data-toggle="modal" href="#myModal" class="thumbnail"><img src="/img/application/Praktikanteneinschaetzung.jpg" alt="Praktikum"></a>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <img src="/img/application/Foto.jpg">
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>