<div class="row">
    <div class="navigation col-md-4 hidden-xs hidden-sm" >
        <div id="navbar" data-spy="affix" data-offset-top="0">
            <div class="navbar-inner">
                <ul class="nav nav-tabs nav-stacked mainNavigation">
                    <li><a href="#wrapper">Home</a></li>
                    <li><a href="#profile">Profile</a></li>
                    <li><a href="#projects">Projects</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>

    </div>
    <div data-target=".mainNavigation" class="col-md-8">
        <div>
            <div class="page-header" id="start">
                <h1>Zur Person <small> That's me</small></h1>
            </div>
            <div class="well well-lg">
                <p class="lead">Hallo,</p>
                <p class="lead">Ich heiße Tom Scheduikat und bin <?php echo $this->age ; ?> Jahre alt.
                Ich lebe zurzeit in Stralsund, einer schönen Stadt im Norden Deutschlands.</p>
                <p class="lead">Zurzeit arbeite ich Hauptberuflich als Softwareentwickler für einen großen deutschen Internetkonzern.
                Hauptsächlich verbringe ich meine Freizeit mit der Familie und kümmere mich um die anderen Sachen
                wenn der Rest schläft. Dann programmiere ich an ein paar von
                meinen eigenen <a href="#projects">Projekten</a> und wenn ich darauf mal keine Lust habe
                dann spiele ich auch ein paar Spiele :D</p>

            </div>
        </div>
        <div>
            <div class="page-header" id="profile">
                <h1>Ein Paar Fakten über mich <small> Yeah</small></h1>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h2 class="panel-title">Allgemein</h2>
                </div>
                <div class="panel-body">
                    <div class="well well-sm"><a href="https://www.xing.com/profiles/Tom_Scheduikat">Xing</a></div>
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 class="panel-title">Qualifikationen</h2>
                </div>
                <div class="panel-body">
                    <div class="well well-sm">PHP</div>
                    <div class="well well-sm">HTML4/5</div>
                    <div class="well well-sm">CSS2/3</div>
                    <div class="well well-sm">Javascript (jQuery)</div>
                    <div class="well well-sm">Zend Framework 1 / 2</div>
                    <div class="well well-sm">MySQL</div>
                    <div class="well well-sm">Doctrine</div>
                    <div class="well well-sm">SVN / Github</div>
                    <div class="well well-sm">Linux/Windows</div>
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2 class="panel-title">Menschliches</h2>
                </div>
                <div class="panel-body">
                    <div class="well well-sm">Teamfähig</div>
                    <div class="well well-sm">Kreativ</div>
                    <div class="well well-sm">Zielorientiert</div>
                    <div class="well well-sm">Orgnisator</div>
                </div>
            </div>
        </div>
        <div>
            <div class="page-header" id="projects">
                <h1>My Projects </h1>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Diese Homepage</h3>
                </div>
                <div class="panel-body">
                    Diese Homepage soll Infos zu meiner Person geben und für eventuell anstehende Bewerbungsgespräche dienen.
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">YuGiOh mDB</h3>
                </div>
                <div class="panel-body">
                    Dies ist meine erste Web App für das Smartphone. Mit Jquery Mobile und PhoneGap realisiert.<br>
                    Diese App sucht anhand von Namen oder Kartennummer, YuGiOh Karten aus einer DB zeigt diese an.
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Cardgame</h3>
                </div>
                <div class="panel-body">
                    Dies ist noch eine Geheime Idee von mir bezüglich eines Kartenspiels für Desktop und Mobile Bereich.
                </div>
            </div>
        </div>
        <div>
            <div class="page-header" id="contact">
                <h1>Contact <small> Please contact me when you have some Questions</small></h1>
            </div>
            <div class="well well-lg">
                <p class="lead">Bitte kontaktiert mich wenn ihr Fragen habt.</p>
                <address>
                    <a href="mailto:#">Tom.Scheduikat@googlemail.com</a>
                </address>
                <p class="lead">Oder schreibt mir einfach bei Xing.</p>
            </div>
        </div>
    </div>
</div>